/* This file is automatically generated. DO NOT EDIT! */

#ifndef _sparsesolver_h
#define _sparsesolver_h


#ifdef _OPENMP
#include <omp.h>
#endif


void sparse_init(int uts, int pad1, int pad2);
/*< sparse init >*/


void sparse_factor(double omega, int n1, int n2, float d1, float d2,
                float **v, int npml, int pad1, int pad2, int uts);
/*< sparse factor>*/


void sparse_solve(int npml, int pad1, int pad2, sf_complex ***f, bool hermite, int ns, int uts);
/*< sparse solver>*/


void sparse_free(int uts);
/*< sparse free>*/

#endif
