/* This file is automatically generated. DO NOT EDIT! */

#ifndef _waveoperator_h
#define _waveoperator_h


/* subroutines for fwi */
float forward_operator(const int uts,
                      const int pad1,
                      const int pad2,
                      const double omega,
                      const int n1,
                      const int n2,
                      const float d1,
                      const float d2,
                      const int npml,
                      const int ns,
                      sf_complex ***f,
                      sf_complex ***obs,
                      bool hermite_false,
                      float **recloc,
                      float **input);
/*< forward operator for fwi for a single frequency >*/


float adjfwi_operator(const int uts,
                      const int pad1,
                      const int pad2,
                      const double omega,
                      const int n1,
                      const int n2,
                      const float d1,
                      const float d2,
                      const int npml,
                      const int ns,
                      sf_complex ***f,
                      sf_complex ***obs,
                      bool hermite_false,
                      bool hermite_true,
                      float **recloc,
                      float **input,
                      float **output);
/*< adjoint operator for fwi for a single frequency >*/


/* subroutines for lsm */
void bornsyn_operator(const int nw,
                      const float ow,
                      const float dw,
                      const int ns,
                      const int n1,
                      const int n2,
                      const int uts,
                      const int pad1,
                      const int pad2,
                      const int npml,
                      const float d1,
                      const float d2,
                      bool hermite_false,
                      float **v,
                      sf_complex ****f,
                      float **recloc,
                      float **input,
                      sf_complex ****output);
/*< born forward operator >*/


void adjlsm_operator(const int nw,
                     const float ow,
                     const float dw,
                     const int ns,
                     const int n1,
                     const int n2,
                     const int uts,
                     const int pad1,
                     const int pad2,
                     const int npml,
                     const float d1,
                     const float d2,
                     bool hermite_false,
                     bool hermite_true,
                     float **v,
                     sf_complex ****f,
                     float **recloc,
                     sf_complex ****input,
                     float **output);
/*< adjoint operator for lsm >*/

#endif
