#! /bin/sh
# shell for Kirchhoff modeling for linear v(x,z)
set -x

 nt=1000 dt=0.004 ft=0.0 tmin=0.2
 kilounits=1
 nxs=11  dxs=0.250 fxs=0.0
 nxo=201 dxo=0.025 fxo=-2.5
 fpeak=5 er=0 ls=1
 susynlv  nt=$nt dt=$dt ft=$ft nxs=$nxs dxs=$dxs fxs=$fxs  fxo=$fxo\
  dxo=$dxo nxo=$nxo tmin=$tmin v00=1.5 dvdx=0.0 dvdz=0. \
  fpeak=$fpeak er=1 ls=1 kilounits=$kilounits verbose=1 \
 	ref="1:1.25,1.25;1.2525,1.25"> data

suwind key=gx min=0 max=2500 < data > data2
