#! /bin/sh
# shell for plotting synthetic data and migrated data

WIDTH=400
HEIGHT=600
WIDTHOFF1=10
WIDTHOFF2=480
WIDTHOFF3=900
HEIGHTOFF1=20

nz=101 dz=25 fz=.0  labelz="Depth (m)"
nx=101 dx=25 fx=0000.0  labelx="Distance (m)"

ximage <vfile  style=seismic legend=1 units=vel cmap=hsv5 \
	n1=$nz d1=$dz f1=$fz grid1=dot label1="$labelz" \
	n2=$nx d2=$dx f2=$fx grid2=dot label2="$labelx" \
	title="Velocity" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF1 ybox=$HEIGHTOFF1 &

suximage<data2  perc=99.5 legend=1 units=amp cmap=hsv5 \
	label1="Time (s)" label2="Midpoint (m)" \
	title="Synthetic Data" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF2 ybox=$HEIGHTOFF1 &

# Plotting migrated data

suximage<kd.data perc=99.9 legend=1 units=amp cmap=rgb0 \
	label1="Depth (km)" label2="Midpoint (km)" \
	title="Kirchhoff Depth Migration" \
	wbox=$WIDTH hbox=$HEIGHT xbox=$WIDTHOFF3 ybox=$HEIGHTOFF1 &
