from rsf.proj import *

# Model variables
m="n1=101 d1=0.01 o1=0 label1=Time unit1=s n2=201 d2=0.01 o2=-1 label2=Midpoint unit2=km"

# Spike variables
k="k1=10,20,50,80,10,20,50,80,10,20,50,80 k2=100,100,100,100,5,5,5,5,195,195,195,195 nsp=12"

# Input velocity and reflectivity
Flow('vel', None, 'spike mag=1. %s'%(m))
Flow('refl', None, 'spike mag=1. %s %s'%(m,k))

Result('refl','grey title="Reflectivity" pclip=100.')

# Kirchhoff modeling
off="nh=1 dh=0.01 h0=0 apt=20"
Flow('dat', 'refl vel', 'mig2 vel=${SOURCES[1]} %s adj=n antialias=1'%(off))

# Kirchhoff migration
Flow('mig', 'dat vel', 'mig2 vel=${SOURCES[1]} %s adj=y antialias=1'%(off))

# Least-squares migration
niter=10
Flow('lsm', 'dat vel mig',
     '''
     conjgrad mig2 vel=${SOURCES[1]} mod=${SOURCES[2]} %s antialias=1 niter=%d
     '''%(off,niter))


Result('dat','grey title="Data" pclip=99.99')
Result('mig','grey title="MIG" pclip=99.99')
Result('lsm','grey title="LSM" pclip=99.99')

End()
